### ISSUE TITLE
Question: Are you sure this is a full boot image?

### ISSUE THREAD

**Issue by MafiaBoys** [Forgo7ten/BootImgTool#1]
Script On   ./unpack-bootimg.pl boot.img
**Question**: Are you sure this is a full boot image?
**My Answer**: No i'am kidding 
**Note**: Don't Uses This P00P script writing by P00P and Stuipd Algorithm

**Comment by Forgo7ten** [comment]
Sorry I didn't understand what you meant. This works great for me, and I'm just making a collection of tools. You can submit related questions under the original [repository](https://github.com/difcareer/BootImgTool).
